### ISSUE TITLE
Make links in Repo description clickable 

### ISSUE THREAD

**Issue by MichaelHancock** [CodeHubApp/CodeHub#212]
Often devs add a website pertaining to their repo in the description. It would be good if you could click these links and have them open in the default browser.

**Comment by travisxcode** [comment]
I'm sorry if this is in the wrong spot, but I need help. I've unsubscribed from getting emails, and I've also muted this thread, to no avail. What do I need to do in order to stop being contacted about CodeHub?

Sent from my iPhone

On Jul 29, 2016, at 5:57 PM, Michael Hancock <notifications@github.com<mailto:notifications@github.com>> wrote:


Often devs add a website pertaining to their repo in the description. It would be good if you could click these links and have them open in the default browser.

-

**Comment by geo1088** [comment]
@traviscode Mute the repo instead of just the issue. From the repo's main page, click the "watch" button, then the "mute" option.

**Comment by travisxcode** [comment]
Thank you so much!

Sent from my iPhone

On Jul 29, 2016, at 8:23 PM, Geo1088 <notifications@github.com<mailto:notifications@github.com>> wrote:


@travisxcode<https://github.com/travisxcode> Mute the repo instead of just the issue. From the repo's main page, click the "watch" button, then the "mute" option.

-
