### ISSUE TITLE
on repo page, topright button usually refuses to work

### ISSUE THREAD

**Issue by wooowooo** [CodeHubApp/CodeHub#244]
topright button doesnt show the menu containing "star", "watch","share" etc

on ios 9.3.3

**Comment by wooowooo** [comment]
seconds after openning repo page ,the star icon shows then the button works.

**Comment by thedillonb** [comment]
When you travel to the repository view, how quickly are you hitting that button? The code will ignore presses until all the repository information loads. This is because some of the menu's buttons, like "Star", "Watch", and "Show" are dependent on the repository loading so they can get state information.

**Comment by thedillonb** [comment]
Closing as this has been addressed in the latest release: 2.14.0.
