### ISSUE TITLE
Pro not working

### ISSUE THREAD

**Issue by gfzabarino** [CodeHubApp/CodeHub#339]
Hey, I just purchased the pro version but I don’t see any private repositories’ data in the app. What do I need to enable this?

**Comment by thedillonb** [comment]
Are these repositories owned by organizations?

**Comment by gfzabarino** [comment]
My bad, I needed permissions, I had to logout and log back in to get requested for that. Maybe it would be nice to ask the user after a purchase to whether present an authorization modal for private repos that can now be used with the App.

**Comment by thedillonb** [comment]
Unfortunately, CodeHub is never aware of any private repositories you may have under an organization if it's not 3rd-party enabled. The app could never tell you if you needed permission or not because, to the app, those organizations, or repos, are just never listed as belonging to you. It's an unfortunately situation but in the app's "walk through" (when you first download it) I try to call it out since a lot of people get bit by it.
