### ISSUE TITLE
HTML code snippet actually rendering

### ISSUE THREAD

**Issue by alexgurr** [CodeHubApp/CodeHub#353]
Someone tried to share some code with me in a comment, but seems to be actually getting rendered? ![Image](https://i.imgur.com/BzlRuP4.jpg)

**Comment by bobjacobsen** [comment]
> Someone tried to share some code with me in a comment, but seems to be actually getting rendered? 
> 

If you put three back quotes on a desperate line before and after, github won’t render or format:

```
Test code with <element>
```

**Comment by garrettw** [comment]
@bobjacobsen But that's not quite it. Notice in the screenshot above, the backticks are visible, which means they're not affecting the output. GitHub itself isn't responsible for this rendering behavior because it sends comments to the CodeHub app in raw form.

Basically this is a potential security hole in CodeHub, depending on exactly which HTML tags are allowed to render. CodeHub may need to convert all raw `<` and `>` to `&lt;`/`&gt;` before displaying the comments.

**Comment by thedillonb** [comment]
I can't quite reproduce this. GitHub actually passes down, in it's API, the sanitized version of the comment that CodeHub uses to render. For example, below I made a comment that looked like this:

```
<img src="https://giant.gfycat.com/WellinformedHonestCaracal.gif">
```

GitHub returns the escaped version of that and CodeHub just renders that:

```
<pre><code>&lt;img src=&quot;https://giant.gfycat.com/WellinformedHonestCaracal.gif&quot;&gt;
</code></pre>
```

My guess here is that your friend did a single back-tick "`" followed by an empty line, then the HTML. In that case, its not assumed to be "code" and is un-escaped. You can even check this by going on GitHub.com and checking out his comment there. If it's in image form then it's just a markdown syntax error.

**Comment by thedillonb** [comment]
Closing this as I believe the original post was user error rather than not converting markdown to HTML correctly. If you believe this is incorrect, reopen it.
