### ISSUE TITLE
Highlight.js plugin for line numbering

### ISSUE THREAD

**Issue by wcoder** [CodeHubApp/CodeHub#364]
Hi! Thanks for app!

I see that you use Highlight.js
https://github.com/CodeHubApp/CodeHub/blob/master/CodeHub/WebViews/SyntaxHighlighterWebView.cshtml#L59

Maybe do you want to use line numbering plugin for Highlight.js?
Looks here: https://github.com/wcoder/highlightjs-line-numbers.js

The plugin is resolved most of the problems of numbering the code.

**Comment by thedillonb** [comment]
Holy cow, this is awesome! Great plugin @wcoder. Definitely going to add it to the project!

**Comment by softwareboy92** [comment]
do not send message to me吕忠迪 (softwareboy)android开发工程师 - 亚信科技（中国）有限公司www.627291991@qq.com
            On 12/15/2017 13:26, Dillon Buchanan wrote: Closed #364 via bdd9aec.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CodeHubApp/CodeHub","title":"CodeHubApp/CodeHub","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/CodeHubApp/CodeHub"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #364 via bdd9aecbd7e3a68ec8b27b581530e4e1a9fe819f."}],"action":{"name":"View Issue","url":"https://github.com/CodeHubApp/CodeHub/issues/364#event-1389008366"}}}

**Comment by thedillonb** [comment]
@softwareboy92 then unsubscribe to the repository. You signed up, you need to unsubscribe.
