### ISSUE TITLE
Cannot see Organisation repos

### ISSUE THREAD

**Issue by nfelger** [CodeHubApp/CodeHub#395]
How do I access my org’s repos? There’s nothing in the sidebar menu, and under profile it just says “no organisations”.

**Comment by garrettw** [comment]
Please look through the closed issues before posting your own to see if your question has already been answered. This is a common problem that has been addressed many times over in previous issues. (#359, #346, #339, #336 - just to name a few)

Please see https://github.com/CodeHubApp/CodeHub#i-cant-find-my-organization. If you can't see your organizations then they have 3rd-party access disabled and you need to request access for the app. CodeHub cannot do this for you - GitHub explicitly designed it to work this way.

**Comment by nfelger** [comment]
Hi garrettw, thank for the pointer. I had no idea clicking “submit feedback” in the app would create a public github issue. My assumption was that this would email support. Bit of an unwelcome surprise and as this is a product I’m paying for (however little it may be), I don’t appreciate being berated for asking dumb questions. I don’t know why it should’ve been obvious to me to visit the project’s repo and search closed issues, or where I should’ve seen the README in the app.

**Comment by garrettw** [comment]
I didn't know you posted it that way -- there is no way for me to know that.
You're actually not the first person to think the "submit feedback" button would privately email support, so that UX seems like something worth taking a closer look at. I can easily see how none of that would have been obvious to you, given how you got here.

@thedillonb -- As I check the UX flow on my phone for this scenario, I notice that, under the "Feedback & Support" tab, there is a button labeled "Submitted Work Items" which just shows all open CodeHub issues. I think that button label might be a bit misleading, because when I saw it, I assumed it meant "work items I've submitted already". I wonder if a better label would be "All Submissions", and then showing both open and closed issues in the list (because if someone has made it to that point, they would probably primarily want to know whether something has been reported or not, and from there to discover whether a solution exists).
@nfelger, your input is welcome on this as well. What would be more clear to you?

**Comment by nfelger** [comment]
@garrettw got it - your reaction makes perfect sense in that light!
As for your suggestions, based on my experience with using the app for all of 5 minutes, I'd say the following would have helped me personally:
- In the app, there's an option for "Suggest a feature" and "Report a bug". I don't see how they're different? I'm assuming both create an issue on Github? I would have one option be "Contact support" (sends an email) and one "Create CodeHub Issue".
- "Submitted Work Items" is indeed confusing. I also thought this would allow me to keep track of support tickets I'd already submitted. This is an app for Github, and the majority of users should be more familiar with the term "issues", so maybe something like "View CodeHub Issues" could work better?
- Maybe automatically add a label to any issues submitted via the app, so that contributors can tell those apart from normal issues.
- Lastly, to address my original issue: under 'profile' -> 'organisations', adding a link at the bottom with text 'Missing organisations?' which goes to https://github.com/CodeHubApp/CodeHub#i-cant-find-my-organization would've helped me solve my problem on my own.

I have no idea if that's what you were after, but I hope you find this perspective useful!

**Comment by garrettw** [comment]
> - In the app, there's an option for "Suggest a feature" and "Report a bug". I don't see how they're different? I'm assuming both create an issue on Github?

I agree, it seems like both of those do the same thing, so two different buttons confuse that a bit. I don't know if Dillon wants people emailing him directly, so if he doesn't, then I guess the best option would be to have one button there, maybe with some text above it describing what it's for / what it will do.

> - Maybe automatically add a label to any issues submitted via the app, so that contributors can tell those apart from normal issues.

Good idea. I would call the label "In-App Feedback".

> - Lastly, to address my original issue: under 'profile' -> 'organisations', adding a link at the bottom with text 'Missing organisations?' which goes to https://github.com/CodeHubApp/CodeHub#i-cant-find-my-organization would've helped me solve my problem on my own.

Also a good idea.

**Comment by thedillonb** [comment]
This is excellent feedback. @nfelger, the original intention of making the app post to GitHub was that my hope was that members of the CodeHub community could probably answer quicker than I could not to make anyone look foolish. In some ways the idea was a success since great contributors, like @garrettw, have been instrumental in getting feedback to the community faster than I am, however, I can completely understand where you were coming from. 

Unfortunately, "Suggest a feature" and "Report a bug" *should* have also been adding a label to the issue which helps to distinguish them and categorize them but it looks like that got broken somehow. I will look into that, and most likely revamp that portion of the app.

**Comment by thedillonb** [comment]
@nfelger I've reworked the support section based on your feedback. In retrospect I'm not sure what I was doing designing it like that - your suggestions make it much clearer.

**Comment by nfelger** [comment]
Amazing - happy to hear my angry entitled-consumer rant has had a positive impact in the end! 😊

**Comment by garrettw** [comment]
Either of you could close this now 😉
