### ISSUE TITLE
Sort stargazers by recent

### ISSUE THREAD

**Issue by danmarshall** [CodeHubApp/CodeHub#431]
When viewing my projects stargazers, would like to see the list in reverse chronological order, as on GitHub.

**Comment by thedillonb** [comment]
This would be nice to draw parity with the site. Unfortunately, GitHub's API does not provide an order parameter so changing it from how it is now is not feasible until they add that. The problem is really around pagination and lazy loading the list. The only way we'd be able to sort them like the site is if we retrieved all of them and then ordered them.
