### ISSUE TITLE
How to create a new repository

### ISSUE THREAD

**Issue by OscarJin** [CodeHubApp/CodeHub#597]
How to create a new repository on the client？

**Comment by BobRocket** [comment]
are u stupid？？？？？

**Comment by pk23488** [comment]
are you serious？



            
            
                
                    
                            
                                
                            
                            
                                947612133
                            
                    
                        
                            
                                    邮箱：947612133@qq.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


            On 06/09/2019 09:40, Oscar Jin wrote: How to create a new repository on the client？



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/CodeHubApp/CodeHub/issues/597?email_source=notifications\u0026email_token=AKBJUE7L2JW2JKP7TZVZY23PZRNSLA5CNFSM4HWIOVK2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GYNHOHQ",

"url": "https://github.com/CodeHubApp/CodeHub/issues/597?email_source=notifications\u0026email_token=AKBJUE7L2JW2JKP7TZVZY23PZRNSLA5CNFSM4HWIOVK2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GYNHOHQ",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by lnootuits** [comment]
What's wrong with you?





------------------ 原始邮件 ------------------
发件人: "Feixu_Yan"<notifications@github.com>;
发送时间: 2019年6月9日(星期天) 上午10:46
收件人: "CodeHubApp/CodeHub"<CodeHub@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [CodeHubApp/CodeHub] How to create a new repository (#597)




             are you serious？
 
 
 
             
             
                 
                     
                             
                                 
                             
                             
                                 947612133
                             
                     
                         
                             
                                     邮箱：947612133@qq.com
                             
                         
                 
             
         Signature is customized by Netease Mail Master
 
 
             On 06/09/2019 09:40, Oscar Jin wrote: How to create a new repository on the client？
 
 
 
 —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
 
 [
 
 {
 
 "@context": "http://schema.org",
 
 "@type": "EmailMessage",
 
 "potentialAction": {
 
 "@type": "ViewAction",
 
 "target": "https://github.com/CodeHubApp/CodeHub/issues/597?email_source=notifications\u0026email_token=AKBJUE7L2JW2JKP7TZVZY23PZRNSLA5CNFSM4HWIOVK2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GYNHOHQ",
 
 "url": "https://github.com/CodeHubApp/CodeHub/issues/597?email_source=notifications\u0026email_token=AKBJUE7L2JW2JKP7TZVZY23PZRNSLA5CNFSM4HWIOVK2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GYNHOHQ",
 
 "name": "View Issue"
 
 },
 
 "description": "View this Issue on GitHub",
 
 "publisher": {
 
 "@type": "Organization",
 
 "name": "GitHub",
 
 "url": "https://github.com"
 
 }
 
 }
 
 ] 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by cppguru** [comment]
Stop it guys or all of you will be reported for destructive behavior.

**Comment by lnootuits** [comment]
------------------ 原始邮件 ------------------
发件人: "Attila Fehér"<notifications@github.com>;
发送时间: 2019年6月9日(星期天) 上午10:58
收件人: "CodeHubApp/CodeHub"<CodeHub@noreply.github.com>;
抄送: "林间"<1933711613@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [CodeHubApp/CodeHub] How to create a new repository (#597)




Stop it guys or all of you will be reported for destructive behavior.

**Comment by lnootuits** [comment]
不要秀智商下限了好吗？



------------------ 原始邮件 ------------------
发件人: "Attila Fehér"<notifications@github.com>; 
发送时间: 2019年6月9日(星期天) 上午10:58
收件人: "CodeHubApp/CodeHub"<CodeHub@noreply.github.com>; 
抄送: "林间"<1933711613@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [CodeHubApp/CodeHub] How to create a new repository (#597)




Stop it guys or all of you will be reported for destructive behavior.

**Comment by cppguru** [comment]
你为什么不尝试表现得像专业人士？ 你现在表现得像一个脾气暴躁的孩子？

**Comment by OscarJin** [comment]
sorry, but what i mean is how to create a new repository in the third-party CodeHub instead of in GitHub.
perhaps all of you above have misunderstood

**Comment by zhanyi22333** [comment]
what？what did i do？ what should i
do？i think i dont use github frequently,so what I did is wrong?


On 06/09/2019 13:38, Oscar Jin wrote:

sorry, but what i mean is how to create a new repository in the third-party CodeHub instead of in GitHub.
perhaps all of you above have misunderstood

**Comment by itguanxu** [comment]
去你妈的




| |
关旭
|
|
邮箱：guanxu176@126.com
|

签名由 网易邮箱大师 定制

On 06/09/2019 13:59, zhanyi22333 wrote:
what？what did i do？ what should i
do？i think i dont use github frequently,so what I did is wrong?


On 06/09/2019 13:38, Oscar Jin wrote:

sorry, but what i mean is how to create a new repository in the third-party CodeHub instead of in GitHub.
perhaps all of you above have misunderstood

**Comment by garrettw** [comment]
To answer this question, you don't create a new repository in the CodeHub app. There would be no reason for doing it there.

**Comment by thedillonb** [comment]
@garrettw is correct.

For those who felt the need to insult or just plain spam the issue: Please don't do it again. If it occurs again then I will block you from the project.
